export const projectType = {
    GET_START_PROJECT_FETCH: 'GET_START_PROJECT_FETCH',
    ADD_NEW_PROJECT: 'ADD_NEW_PROJECT',
    SET_NUW_PROJECT_REDUCER: 'SET_NUW_PROJECT_REDUCER',
    DELETE_PROJECT_ITEM: "DELETE_PROJECT_ITEM",
    GET_EDIT_PROJECT_ITEM: "GET_EDIT_PROJECT_ITEM",
    SET_ITEM_PROJECT_REDUCER_EDITE: ' SET_ITEM_PROJECT_REDUCER_EDITE',
    GET_ID_PROJECT_EDITE: " GET_ID_PROJECT_EDITE",
}