export const membersActionType = {
    START_FETCH_MEMBERS: 'START_FETCH_MEMBERS',
    SET_MEMBERS_REDUCER: 'SET_MEMBERS_REDUCER',
    ADD_NEW_MEMBERS_REDUCER: 'ADD_NUE_MEMBERS_REDUCER',
    GET_ID_DELETE_MEMBERS_ITEM: 'GET_ID_DELETE_MEMBERS_ITEM',
    SET_NEW_DATE_LIST_FILTER_MEMBERS: ' SET_NEW_DATE_LIST_DELETE_MEMBERS',
    SET_MEMBER_NEW_LIST: 'SET_MEMBER_NEW_LIST',
    GET_ITEM_EDIT_MEMBERS: 'GET_ITEM_EDIT_MEMBERS',
    EDITE_MEMBERS_ITEM: ' EDITE_MEMBERS_ITEM',
    SET_NEW_DATE_EDITE_MEMBERS_LIST: 'SET_NEW_DATE_EDITE_MEMBERS_LIST',
    GET_SEARCH_TEXT_VALUE: 'GET_SEARCH_TEXT_VALUE',
}
