export const commentType = {
    GET_ID_TASK_ITEM: 'GET_ID_TASK_ITEM',
    SET_TASK_ITEM_REDUCER: " SET_TASK_ITEM_REDUCER",
    GET_TEXT_VALUE_COMMENT: "GET_TEXT_VALUE_COMMENT",
    SET_COMMENT_TASK_ITEM: 'SET_COMMENT_TASK_ITEM'
}