export const taskType = {
    ADD_TASK_PROJECT_ITEM_DETALISED: 'ADD_TASK_PROJECT_ITEM_DETALISED',
    SET_TASK_DETALISED_REDUCER: ' SET_TASK_DETALISED_REDUCER',
    GET_ITEM_NEW_TASK: 'GET_ITEM_NEW_TASK',
    GET_FILTER_TASK_PROJECT_ITEM: 'GET_FILTER_TASK_PROJECT_ITEM',
    SET_FILTER_TASK_REDUCER: 'SET_ITEM_NEW_TASK_REDUCER',
    GET_ITEM_TASK_EDITE: "GET_ITEM_TASK_EDITE",
    SET_TASK_EDIT_DATE_REDUCER: ' SET_TASK_EDIT_DATE_REDUCER',
    GET_ITEM_TASK_VALUE_EDIT: " GET_ITEM_TASK_VALUE_EDIT",
    SET_ITEM_ALL_REDUCER_TASK_EDITE: "SET_ITEM_ALL_REDUCER_TASK_EDITE",
    SET_REDUCER_ALL_TASK: 'SET_REDUCER_ALL_TASK',
    GET_ITEM_TASK_DELETE: "GET_ITEM_TASK_DELETE",
}