export const loginType = {
    SET_DATE_LOGIN_LOGOUT_REDUCER: 'SET_DATE_LOGIN_LOGOUT_REDUCER',
    GET_ID_LOGIN_ADMIN: 'GET_ID_LOGIN_ADMIN',
    SET_USER_ITEM_REDUCER: 'SET_USER_ITEM_REDUCER',
    GET_USER_DATA: 'GET_USER_DATA',
    ERROR_MESSING_LOGIN_USER: 'ERROR_MESSING_LOGIN_USER',
    GET_USER_LOGIN_ITEM: ' GET_USER_LOGIN_ITEM',
    FETCH_TOKEN_ITEM_USER: 'FETCH_TOKEN_ITEM_USER'
}